apiVersion: v1
kind: Service
metadata:
  name: labubu-shop
spec:
  selector:
    app: labubu-shop
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: metrics
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer
    